# Generated by Django 2.2.2 on 2019-10-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('appaterno', models.CharField(max_length=25)),
                ('apmaterno', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
