# Generated by Django 2.2.2 on 2019-10-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20191001_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('idAvatar', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(max_length=50)),
                ('puntosAvatar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCurso', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='run',
            field=models.CharField(default=1, max_length=12),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='idTipoUsuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='idAvatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Avatar'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idCurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Curso'),
        ),
    ]
