# Generated by Django 2.2.2 on 2019-10-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20191001_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.CharField(default='19.318.877-k', max_length=12),
        ),
    ]
