# Generated by Django 2.2.4 on 2019-10-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20191001_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Respuestas',
            new_name='Respuesta',
        ),
    ]
