# Generated by Django 2.2.6 on 2019-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybubble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
